#!/bin/sh

echo "Hello World"

# Mount necessary filesystems
mount -t devtmpfs dev /dev

# Display available devices for debugging
echo "Available devices:"
ls /dev
echo "Partition /dev/sda1 does not exist. Creating and formatting partition."
parted /dev/sda --script mklabel msdos
parted /dev/sda --script mkpart primary ext4 0% 100%
mkfs.ext4 /dev/sda1

# Mount the main partition
mount -t ext4 /dev/sda1 /mnt
if [ $? -ne 0 ]; then
    echo "Error mounting the filesystem. Starting a shell for debugging."
    exec /bin/sh
fi

# Copy all files from the current root filesystem to the new root filesystem
echo "Copying current root filesystem to new permanent partition..."
cp -a / /mnt

# Check if /sbin/init exists in the new root filesystem
if [ ! -f /mnt/sbin/init ]; then
    echo "/mnt/sbin/init does not exist in the new root filesystem. Starting a shell for debugging."
    exec /bin/sh
fi

# Mount necessary filesystems
mount -t proc proc /proc
mount -t sysfs sys /sys
#mount -t devtmpfs dev /dev

echo ""
echo "Hello World. Temporary fs finish loaded!"
# Check if /sbin/init exists in the new root filesystem
if [ ! -f /sbin/init ]; then
    echo "/sbin/init does not exist in the temp root filesystem. Starting a shell for debugging."
    exec /bin/sh
fi

/bin/sh
echo "Hello World. Switch from temp fs to permanent fs!"
echo "Current PID: $$"
# Switch the root to /mnt/ and start init
switch_root /mnt /sbin/init

echo ""
echo "Hello World. Permanent fs finish loaded!"
/bin/sh
exec switch_root /mnt /sbin/init
